//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Cake.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Reflection;

[assembly: AssemblyProduct("Dropcraft")]
[assembly: AssemblyVersion("0.1.0.0")]
[assembly: AssemblyFileVersion("0.1.0.0")]
[assembly: AssemblyInformationalVersion("0.1.0+25.Branch.master.Sha.4422312f3718d9c2d458ff89a4c044f88286f378")]
[assembly: AssemblyCopyright("Copyright © Andrei Marukovich")]

