//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Cake.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Reflection;

[assembly: AssemblyProduct("Dropcraft")]
[assembly: AssemblyVersion("0.1.0.0")]
[assembly: AssemblyFileVersion("0.1.0.0")]
[assembly: AssemblyInformationalVersion("0.1.0+21.Branch.master.Sha.1b8cb69b9021ec7951be33de6901643931b9f713")]
[assembly: AssemblyCopyright("Copyright © Andrei Marukovich")]

